### PR TITLE
feat: Support to set ignored URLProtocol classes

### PR DESCRIPTION
**Pull request by HoaPham98**
I have an idea to prevent the duplicate records issue when using with URLProtocol. The issue has been mentioned in: https://github.com/ProxymanApp/atlantis/issues/154

### CODE REVIEW

**Review by NghiaTranUIT — CHANGES_REQUESTED** [review]
Thanks for the PR, but may I ask whether or not you test it?

I tested and the bug hasn't fixed yet.

https://github.com/user-attachments/assets/1e9418f7-545c-4738-a725-e1199bb5f132

---------
Set a breakpoint, I confirmed that it jumps to the `return nil`. However, 2 requests are still appeared.
```
            if checkShouldIgnore(on: request) {
                return nil
            }
```

**Comment by HoaPham98** [comment]
> Thanks for the PR, but may I ask whether or not you test it?
> 
> I tested and the bug hasn't fixed yet.
> 
>  CleanShot.2024-11-07.at.13.20.13.mp4 
> Set a breakpoint, I confirmed that it jumps to the `return nil`. However, 2 requests are still appeared.
> 
> ```
>             if checkShouldIgnore(on: request) {
>                 return nil
>             }
> ```

Oh, I see. If with my above code, it won't work. But if you modify the request in method startLoading, it will work
```swift
override class func canonicalRequest(for request: URLRequest) -> URLRequest {
        return request
    }
    
  override func startLoading() {
      var request = request
      request.addValue("Test value", forHTTPHeaderField: "Custom-Header")
      URLSession.shared.dataTask(with: request) { data, response, error in
          if let error {
              self.client?.urlProtocol(self, didFailWithError: error)
          } else if let response {
              self.client?.urlProtocol(self, didReceive: response, cacheStoragePolicy: .notAllowed)
              if let data {
                  self.client?.urlProtocol(self, didLoad: data)
              }
          }
          self.client?.urlProtocolDidFinishLoading(self)
      }.resume()
  }
```

I will recheck my solution. Feel free to discuss with me :D

**Comment by HoaPham98** [comment]
https://github.com/user-attachments/assets/f7d106dc-2b2b-4b30-a863-5a89baec379f

**Comment by HoaPham98** [comment]
Hi @NghiaTranUIT , any news?

**Pull request merged**
